import { useCallback, useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import type { InitialEntry, PreviewRenderer } from '@distri/fs'
import { FileWorkspaceWithChat, IndexedDbFilesystem } from '@distri/fs'
import { useAgent } from '@distri/react'
import { Header } from '@/components/ui/header'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Skeleton } from '@/components/ui/skeleton'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Badge } from '@/components/ui/badge'
import { BACKEND_URL } from '@/constants'
import { useInitialization } from '@/components/TokenProvider'
import { toast } from 'sonner'
import { Save, Sparkles } from 'lucide-react'
import { formatDistanceToNow } from 'date-fns'
import { uuidv4 } from '@distri/core'

const API_BASE_URL = `${BACKEND_URL}/api/v1`
const WORKSPACE_PREFIX = 'distri-skill'
const DEFAULT_SCRIPT_PATH = 'scripts/main.ts'
const DEFAULT_README_PATH = 'README.md'
const DEFAULT_AGENT_INSTRUCTIONS = `You are the runtime agent for this skill. Read the provided scripts, coordinate tools, and give concise responses. Ask for clarification before taking destructive actions.`

const DEFAULT_MOD_TS = `import { createTool } from '@distri/react'

const demoTool = createTool(
  'demo_tool',
  'Echoes whatever input it receives',
  {
    type: 'object',
    properties: {
      message: {
        type: 'string',
        description: 'Text to echo back',
      },
    },
    required: ['message'],
  },
  async ({ message }: { message: string }) => ({
    echoed: message,
    timestamp: new Date().toISOString(),
  }),
)

export default {
  integrations: [
    {
      name: 'sample_skill',
      tools: [demoTool],
    },
  ],
}
`

const DEFAULT_DISTRI_TOML = `[package]\nname = "sample_skill"\nversion = "0.1.0"\ndescription = "Sample Distri skill generated by the designer"\n\n[integrations.sample_skill]\ntools = ["demo_tool"]\n`

const DEFAULT_SAMPLE_HTTP = `### Demo tool invocation via distri-server\nPOST {{DISTRI_API_URL}}/api/v1/tools/demo_tool\nContent-Type: application/json\n\n{\n  "message": "Hello from the Skill Designer"\n}\n`

const DEFAULT_ENTRIES: InitialEntry[] = [
  {
    path: DEFAULT_README_PATH,
    type: 'file',
    content: '# New Distri Skill\n\nUse the workspace to iterate on scripts, docs, and metadata for your skill.',
  },
  {
    path: DEFAULT_SCRIPT_PATH,
    type: 'file',
    content: `type SkillInput = Record<string, unknown>\n\nexport async function runSkill(input: SkillInput) {\n  return {\n    status: 'ok',\n    received: input,\n  }\n}\n`,
  },
  {
    path: 'mod.ts',
    type: 'file',
    content: DEFAULT_MOD_TS,
  },
  {
    path: 'distri.toml',
    type: 'file',
    content: DEFAULT_DISTRI_TOML,
  },
  {
    path: 'samples',
    type: 'directory',
  },
  {
    path: 'samples/demo.http',
    type: 'file',
    content: DEFAULT_SAMPLE_HTTP,
  },
]

const TODO_ITEMS = [
  'Add validation feedback for script exports and metadata',
  'Support loading existing skills for editing',
  'Surface execution history alongside the designer',
]

type SkillExport =
  | { type: 'workflow'; agent_name: string }
  | { type: 'tool'; name: string; description?: string | null }

type SkillFileKind = 'script' | 'markdown' | 'asset'

interface SkillFile {
  path: string
  content: string
  kind: SkillFileKind
  export?: SkillExport
}

interface SkillMetadata {
  version: string
  tags: string[]
}

interface SkillAgentDefinition {
  name: string
  description?: string
  instructions?: string
  tool_format?: string
  [key: string]: any
}

interface Skill {
  id: string
  name: string
  description: string
  metadata: SkillMetadata
  agent_definition: SkillAgentDefinition
  files: SkillFile[]
  created_at?: string
  updated_at?: string
}

const currentThreadId = (scope: string) => {
  if (typeof window === 'undefined') {
    return uuidv4()
  }
  const storageKey = `${WORKSPACE_PREFIX}:${scope}:threadId`
  const cached = window.localStorage.getItem(storageKey)
  if (cached) return cached
  const generated = uuidv4()
  window.localStorage.setItem(storageKey, generated)
  return generated
}

const slugify = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')

const determineKind = (path: string, scriptPath: string): SkillFileKind => {
  if (path === scriptPath) return 'script'
  if (/\.(ts|tsx|js|jsx)$/i.test(path)) return 'script'
  if (path.toLowerCase().endsWith('.md')) return 'markdown'
  return 'asset'
}

const formatTimestamp = (iso?: string | null) => {
  if (!iso) return null
  const date = new Date(iso)
  if (Number.isNaN(date.getTime())) return null
  return formatDistanceToNow(date, { addSuffix: true })
}

const SkillDesignerPage = () => {
  const { skillId } = useParams<{ skillId: string }>()
  const navigate = useNavigate()
  const { token } = useInitialization()
  const { agent, loading: agentLoading, error: agentError } = useAgent({ agentIdOrDef: 'scripter' })

  const [skill, setSkill] = useState<Skill | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [saving, setSaving] = useState(false)
  const [isMetadataDialogOpen, setMetadataDialogOpen] = useState(false)

  const [skillName, setSkillName] = useState('')
  const [description, setDescription] = useState('')
  const [tags, setTags] = useState('')
  const [agentName, setAgentName] = useState('')
  const [agentInstructions, setAgentInstructions] = useState(DEFAULT_AGENT_INSTRUCTIONS)
  const [metadataVersion, setMetadataVersion] = useState('0.1.0')
  const [exposureType, setExposureType] = useState<'workflow' | 'tool'>('workflow')
  const [toolName, setToolName] = useState('runSkill')
  const [toolDescription, setToolDescription] = useState('Entry point for this skill')
  const [scriptPath, setScriptPath] = useState(DEFAULT_SCRIPT_PATH)
  const [lastSavedAt, setLastSavedAt] = useState<number | null>(null)

  const projectId = useMemo(
    () => `${WORKSPACE_PREFIX}-${skillId ?? 'new'}`,
    [skillId],
  )
  const filesystem = useMemo(
    () => IndexedDbFilesystem.forProject(projectId),
    [projectId],
  )

  const threadId = useMemo(
    () => currentThreadId(skillId ?? 'new'),
    [skillId],
  )

  const previewRenderer: PreviewRenderer = useCallback(({ path, content }) => {
    if (path.toLowerCase().endsWith('.md')) {
      return (
        <div className="prose prose-invert max-w-none text-xs">
          {content.split(/\n{2,}/).map((block, idx) => (
            <p key={idx} className="whitespace-pre-wrap">{block}</p>
          ))}
        </div>
      )
    }
    return <pre className="text-xs whitespace-pre-wrap break-words">{content}</pre>
  }, [])

  const clearWorkspace = useCallback(async () => {
    const entries = await filesystem.listDirectory('', true)
    const sorted = entries
      .filter((entry) => entry && entry !== '.')
      .sort((a, b) => b.length - a.length)
    for (const entry of sorted) {
      await filesystem.deleteEntry(entry, true).catch(() => { })
    }
  }, [filesystem])

  const seedWorkspaceWithDefaults = useCallback(
    async (wipeExisting = true) => {
      try {
        if (wipeExisting) {
          await clearWorkspace()
        }
        for (const entry of DEFAULT_ENTRIES) {
          if (entry.type === 'directory') {
            await filesystem.createDirectory(entry.path)
          } else if (typeof entry.content === 'string') {
            await filesystem.writeFile(entry.path, entry.content)
          }
        }
      } catch (err) {
        console.warn('Failed to seed workspace with defaults', err)
      }
    },
    [clearWorkspace, filesystem],
  )

  const primeWorkspace = useCallback(
    async (data: Skill) => {
      try {
        await clearWorkspace()
        if (!data.files || data.files.length === 0) {
          await seedWorkspaceWithDefaults(false)
          return
        }
        for (const file of data.files) {
          await filesystem.writeFile(file.path, file.content)
        }
      } catch (err) {
        console.warn('Failed to sync workspace with skill files', err)
      }
    },
    [clearWorkspace, filesystem, seedWorkspaceWithDefaults],
  )

  const collectWorkspaceFiles = useCallback(
    async (): Promise<SkillFile[]> => {
      const result: SkillFile[] = []
      try {
        const entries = await filesystem.listDirectory('', true)
        const unique = Array.from(new Set(entries.filter((entry) => entry && entry !== '.')))
        for (const entry of unique) {
          try {
            const info = await filesystem.getFileInfo(entry)
            if (!info.is_file) {
              continue
            }
            const file = await filesystem.readFile(entry)
            result.push({
              path: entry,
              content: file.content,
              kind: determineKind(entry, scriptPath),
            })
          } catch (err) {
            console.warn(`Failed to collect workspace entry ${entry}`, err)
          }
        }
      } catch (err) {
        console.warn('Failed to enumerate workspace files', err)
      }
      return result
    },
    [filesystem, scriptPath],
  )

  const loadSkill = useCallback(async () => {
    if (!skillId) {
      setSkill(null)
      setLoading(false)
      setLastSavedAt(null)
      setScriptPath(DEFAULT_SCRIPT_PATH)
      await seedWorkspaceWithDefaults()
      return
    }
    setLoading(true)
    setError(null)
    try {
      const response = await fetch(`${API_BASE_URL}/skills/${encodeURIComponent(skillId)}`, {
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
      })
      if (!response.ok) {
        const message = await response.text()
        throw new Error(message || 'Failed to load skill')
      }
      const data: Skill = await response.json()
      setSkill(data)
      setMetadataVersion(data.metadata?.version ?? '0.1.0')
      setLastSavedAt(data.updated_at ? Date.parse(data.updated_at) : null)
      await primeWorkspace(data)
    } catch (err) {
      console.error(err)
      setError(err instanceof Error ? err.message : 'Failed to load skill')
    } finally {
      setLoading(false)
    }
  }, [skillId, token, primeWorkspace, seedWorkspaceWithDefaults])

  useEffect(() => {
    if (skill) {
      setSkillName(skill.name)
      setDescription(skill.description ?? '')
      setTags((skill.metadata?.tags ?? []).join(', '))
      setAgentName(skill.agent_definition?.name ?? '')
      setAgentInstructions(
        skill.agent_definition?.instructions?.trim() || DEFAULT_AGENT_INSTRUCTIONS,
      )
      setMetadataVersion(skill.metadata?.version ?? '0.1.0')
      const scriptFile = skill.files.find((file) => file.kind === 'script')
      setScriptPath(scriptFile?.path ?? DEFAULT_SCRIPT_PATH)
      if (scriptFile?.export && scriptFile.export.type === 'tool') {
        setExposureType('tool')
        setToolName(scriptFile.export.name)
        setToolDescription(scriptFile.export.description ?? '')
      } else {
        setExposureType('workflow')
        setToolName('runSkill')
        setToolDescription('Entry point for this skill')
      }
      if (skill.updated_at) {
        setLastSavedAt(Date.parse(skill.updated_at))
      }
    }
  }, [skill])

  useEffect(() => {
    void loadSkill()
  }, [loadSkill])

  const handleSaveSkill = useCallback(async () => {
    if (!token) {
      toast.error('Authentication token missing')
      return
    }
    setSaving(true)
    try {
      const preparedName = skillName.trim() || 'Untitled Skill'
      const preparedDescription = description.trim()
      const tagList = tags
        .split(',')
        .map((tag) => tag.trim())
        .filter(Boolean)

      const derivedAgentName = slugify(agentName) || slugify(preparedName) || 'distri_skill_agent'
      const trimmedInstructions = agentInstructions.trim() || DEFAULT_AGENT_INSTRUCTIONS

      const workspaceFiles = await collectWorkspaceFiles()
      if (!workspaceFiles.length) {
        throw new Error('Workspace is empty — add at least one file before saving')
      }

      const scriptFile = workspaceFiles.find((file) => file.kind === 'script')
      if (!scriptFile) {
        throw new Error('Skill must include at least one script file (.ts/.js)')
      }

      const filesPayload = workspaceFiles.map((file) => ({
        path: file.path,
        content: file.content,
        kind: file.kind,
        export:
          file.path === scriptPath
            ? exposureType === 'workflow'
              ? { type: 'workflow' as const, agent_name: derivedAgentName }
              : {
                type: 'tool' as const,
                name: toolName.trim() || 'runSkill',
                description: toolDescription.trim() || undefined,
              }
            : undefined,
      }))

      const updatedAgentDefinition: SkillAgentDefinition = {
        ...(skill?.agent_definition ?? {}),
        name: derivedAgentName,
        description: preparedDescription || skill?.agent_definition?.description || `Skill agent for ${preparedName}`,
        instructions: trimmedInstructions,
        tool_format: 'provider',
      }

      const payload = {
        name: preparedName,
        description: preparedDescription,
        agent_definition: updatedAgentDefinition,
        files: filesPayload,
        metadata: {
          version: metadataVersion || '0.1.0',
          tags: tagList,
        },
      }

      const targetId = skill?.id ?? skillId
      const isUpdate = Boolean(targetId)
      const url = isUpdate
        ? `${API_BASE_URL}/skills/${encodeURIComponent(targetId!)}`
        : `${API_BASE_URL}/skills`

      const response = await fetch(url, {
        method: isUpdate ? 'PUT' : 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(payload),
      })

      if (!response.ok) {
        const errorText = await response.text()
        throw new Error(errorText || 'Failed to save skill')
      }

      const saved: Skill = await response.json()
      setSkill(saved)
      setLastSavedAt(saved.updated_at ? Date.parse(saved.updated_at) : Date.now())
      await primeWorkspace(saved)

      if (!skillId && saved.id) {
        navigate(`/home/skills/${encodeURIComponent(saved.id)}`, { replace: true })
      }

      toast.success('Skill saved to distri-server')
    } catch (err) {
      console.error('Skill save failed', err)
      toast.error(err instanceof Error ? err.message : 'Unknown error while saving')
    } finally {
      setSaving(false)
    }
  }, [
    agentInstructions,
    agentName,
    collectWorkspaceFiles,
    description,
    metadataVersion,
    navigate,
    primeWorkspace,
    scriptPath,
    skill,
    skillId,
    skillName,
    tags,
    token,
    toolDescription,
    toolName,
    exposureType,
  ])

  const workspaceInitialEntries = useMemo(() => {
    if (!skill || !Array.isArray(skill.files) || skill.files.length === 0) {
      return DEFAULT_ENTRIES
    }
    return []
  }, [skill])

  const missingSkillId = !skillId

  if (agentLoading) {
    return (
      <div className="flex h-full flex-col gap-6 p-6">
        <Skeleton className="h-8 w-56" />
        <Skeleton className="h-[520px] w-full" />
      </div>
    )
  }

  if (agentError || !agent) {
    return (
      <div className="flex h-full flex-col items-center justify-center gap-4 px-6 text-center">
        <p className="text-sm text-muted-foreground">
          Unable to load the Scripter agent. Ensure it is registered on the backend before editing skills.
        </p>
        <Button variant="secondary" onClick={() => navigate('/home/skills')}>
          Back to skills
        </Button>
      </div>
    )
  }

  if (loading) {
    return (
      <div className="flex h-full flex-col gap-6 p-6">
        <Skeleton className="h-8 w-64" />
        <Skeleton className="h-[520px] w-full" />
      </div>
    )
  }

  if (error) {
    return (
      <div className="flex h-full flex-col items-center justify-center gap-4 px-6 text-center">
        <p className="text-sm text-muted-foreground">{error}</p>
        <Button variant="secondary" onClick={() => navigate('/home/skills')}>
          Back to skills
        </Button>
      </div>
    )
  }

  const lastSavedLabel =
    formatTimestamp(skill?.updated_at) || (lastSavedAt ? formatTimestamp(new Date(lastSavedAt).toISOString()) : null)

  return (
    <div className="flex h-full flex-col">
      <Header
        title={skillName || 'Skill Designer'}
        subtitle={
          <span className="flex items-center gap-2 text-xs text-muted-foreground">
            <Sparkles className="h-3.5 w-3.5" />
            Pair the Scripter agent with the workspace to build new skills.
          </span>
        }
        rightElement={
          <div className="flex items-center gap-2">
            {lastSavedLabel ? (
              <Badge variant="outline" className="text-[10px] font-normal">
                Saved {lastSavedLabel}
              </Badge>
            ) : null}
            <Button variant="outline" size="sm" onClick={() => setMetadataDialogOpen(true)}>
              Edit metadata
            </Button>
            <Button onClick={handleSaveSkill} disabled={saving} size="sm">
              <Save className="mr-2 h-4 w-4" />
              {saving ? 'Saving…' : 'Save skill'}
            </Button>
          </div>
        }
      />

      {missingSkillId ? (
        <div className="mx-4 mb-3 rounded-lg border border-dashed border-yellow-500/50 bg-yellow-500/10 p-3 text-xs text-yellow-900">
          <p>
            This workspace is not yet registered in the catalog. Save it once to create a skill ID and enable metadata editing.
          </p>
        </div>
      ) : null}

      <div className="flex-1 overflow-hidden px-4 pb-6 h-full">

        <FileWorkspaceWithChat
          projectId={projectId}
          filesystem={filesystem}
          initialEntries={workspaceInitialEntries}
          previewRenderer={previewRenderer}
          onSaveFile={async (tab) => {
            await filesystem.writeFile(tab.path, tab.content)
          }}
          defaultFilePath={scriptPath}

          chat={{
            agent,
            threadId,
            title: 'Scripter',
          }}
          height="calc(100vh - 200px)"
        />

      </div>

      <Dialog open={isMetadataDialogOpen} onOpenChange={setMetadataDialogOpen}>
        <DialogContent className="max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Edit skill metadata</DialogTitle>
            <DialogDescription>
              Update the descriptive information, agent settings, and export configuration for this skill.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-2">
            <div className="space-y-2">
              <Label htmlFor="skill-name">Skill name</Label>
              <Input
                id="skill-name"
                value={skillName}
                placeholder="Customer onboarding skill"
                onChange={(event) => setSkillName(event.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="skill-description">Description</Label>
              <Textarea
                id="skill-description"
                value={description}
                placeholder="Short summary of how this skill should behave"
                onChange={(event) => setDescription(event.target.value)}
                rows={4}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="skill-tags">Tags</Label>
              <Input
                id="skill-tags"
                value={tags}
                placeholder="automation, onboarding"
                onChange={(event) => setTags(event.target.value)}
              />
              <p className="text-xs text-muted-foreground">Separate tags with commas to improve discoverability.</p>
            </div>

            <div className="space-y-2">
              <Label htmlFor="agent-name">Agent name</Label>
              <Input
                id="agent-name"
                value={agentName}
                placeholder="onboarding_skill_agent"
                onChange={(event) => setAgentName(event.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="agent-instructions">Agent instructions</Label>
              <Textarea
                id="agent-instructions"
                value={agentInstructions}
                onChange={(event) => setAgentInstructions(event.target.value)}
                rows={4}
              />
            </div>

            <div className="space-y-2">
              <Label>Primary script export</Label>
              <Select value={exposureType} onValueChange={(value) => setExposureType(value as 'workflow' | 'tool')}>
                <SelectTrigger>
                  <SelectValue placeholder="Select export" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="workflow">Workflow agent</SelectItem>
                  <SelectItem value="tool">Tool</SelectItem>
                </SelectContent>
              </Select>
              <p className="text-xs text-muted-foreground">Choose whether the main script exports a workflow agent or a tool.</p>
            </div>

            {exposureType === 'tool' && (
              <div className="space-y-3 rounded-lg border border-border/80 p-4">
                <div className="space-y-2">
                  <Label htmlFor="tool-name">Tool name</Label>
                  <Input
                    id="tool-name"
                    value={toolName}
                    placeholder="runSkill"
                    onChange={(event) => setToolName(event.target.value)}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="tool-description">Tool description</Label>
                  <Textarea
                    id="tool-description"
                    value={toolDescription}
                    placeholder="Describe what this tool does"
                    rows={3}
                    onChange={(event) => setToolDescription(event.target.value)}
                  />
                </div>
              </div>
            )}

            <div className="space-y-2 rounded-lg border border-dashed border-border/80 p-4">
              <p className="text-xs font-medium text-muted-foreground uppercase">Workspace TODOs</p>
              <ul className="space-y-2 text-xs text-muted-foreground">
                {TODO_ITEMS.map((item) => (
                  <li key={item} className="flex items-start gap-2">
                    <span className="mt-1 inline-block h-1.5 w-1.5 rounded-full bg-primary" aria-hidden />
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setMetadataDialogOpen(false)}>
              Close
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}

export default SkillDesignerPage
