// @distri/angular — Signal-based Angular services over @distri/state.
//
// Deliberately NOT `@Injectable()`-decorated classes: Angular's Ivy DI
// factories are only generated by Angular's own compiler (ngtsc), which
// would require adopting the full Angular Package Format / ng-packagr
// toolchain just to ship plain service classes. Instead these are plain
// factory functions returning Signals — buildable with the same `tsup`
// pipeline as every other package here, and usable from any Angular DI
// style (a `useFactory` provider, or called directly in a component field
// initializer).
export * from './adapter';
export * from './agent';
export * from './chat';
export * from './provider';

// Components ship from the same entry point, so published consumers have a
// single import path (`@distri/angular`) and — critically — only ever load ONE
// copy of the module. Two copies means two distinct DISTRI_SERVICE
// InjectionTokens, and <distri-chat> silently never receives the client.
export * from './components';
